version: "3"

services:
  article-service:
    build: ./article-service
    ports:
      - "50051:50051"
    volumes:
      - ./article-service:/app

  categorie-service:
    build: ./categorie-service
    ports:
      - "3001:3001"
    volumes:
      - ./categorie-service:/app

  api-gateway:
    build: ./api-gateway
    ports:
      - "4000:4000"
    volumes:
      - ./api-gateway:/app
    depends_on:
      - article-service
      - categorie-service
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
